-- ═══════════════════════════════════════════════════════════════════════════
--  SecureMoney — Sample / Demo Data
--  Run AFTER setup_db.sql:  mysql -u root -p securemoney < scripts/sample_data.sql
--
--  Demo credentials (plaintext — for development only):
--    User 1:  Esau.magaro@securemoney.tz / Esau.magaro
--    User 2:  jane.smith@securemoney.tz / TestPass@2026!
--    Admin:   admin / Admin@SecureMoney2026!
--
--  NOTE: Password hashes and encrypted balances below were generated by the
--  application's crypto engine. Do NOT change these values manually.
--  To regenerate: python scripts/seed_demo.py
-- ═══════════════════════════════════════════════════════════════════════════

USE securemoney;

-- Demo data is inserted via the application's Python seed script (scripts/seed_demo.py)
-- to ensure all cryptographic operations go through the crypto_utils module.
-- This SQL file serves as documentation of the expected schema state.

-- To seed the database with demo data, run:
--   python scripts/seed_demo.py

SELECT 'Run scripts/seed_demo.py to insert demo users with proper crypto.' AS note;
